name: Rust

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        name: Check format
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        name: Run clippy
        with:
          command: clippy
          args: --all-targets --locked -- -D warnings
      - uses: actions-rs/cargo@v1
        name: Run tests
        with:
          command: test
